# Generated by Django 3.2.13 on 2022-06-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendance',
            old_name='rollnumber',
            new_name='student',
        ),
    ]
