# Generated by Django 3.2.13 on 2022-06-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_student_attendance_arrivaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='arrivaltime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
