# Generated by Django 3.2.13 on 2022-06-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_student_attendance_arrivaltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20, verbose_name='Class Name')),
                ('shortname', models.CharField(max_length=10, verbose_name='Short Name')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30, verbose_name='School')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
            ],
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.DeleteModel(
            name='student_attendance',
        ),
        migrations.AddField(
            model_name='classe',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.department'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ManyToManyField(to='MainApp.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='currentclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.classe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.department'),
        ),
    ]
