# Generated by Django 3.2.13 on 2022-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20220628_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='fullname',
            field=models.CharField(max_length=20, unique=True, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='shortname',
            field=models.CharField(max_length=10, unique=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.CharField(max_length=50, verbose_name='School'),
        ),
    ]
